Update to leaflet-node 2.0.18
- Previous error at line 274 is fixed
- New error at line 327 in patchMapPrototype
  Error: Cannot read properties of undefined (reading 'prototype')
- Likely L.Map is undefined when trying to patch it